
#ifndef PARALLELCONSTANTS
#define PARALLELCONSTANTS

#define CHANNEL_COUNTS 72
#define PARNUM 4
#define DATANUM 8
#define MATRIXNUM 32

#define WARP_SIZE 32

#define THREADS_RESOLVE 512
#define ELEMS_RESLOVE 2  //每个线程处理的元素个数

#define THREADS_LMCURVE 256
#define ELEMS_LMCURVE 12 

#define THREADS_QUICKLINEFIT 512
#define ELEMS_QUICKLINEFIT 2

#define THREADS_CONVERT 128
#define ELEMS_CONVERT 32

#define THREADS_MERGESORT 512
#define ELEMS_MERGESORT 2


#define SUB_BLOCK_SIZE 256
#define THREADS_GEN_RANKS 128

#define THREADS_PADDING 128
#define ELEMS_PADDING 32

#define THREADS_COINTIME 512
#define ELEMS_COINTIME 16

#define MAX_VAL DBL_MAX 


#define MAX_ITER 100
#define MIN_SETP 1e-12
#define GTOL 1e-12
#define DERIV_STEP 1e-5

#define BUF_MAXLEN 1152
#define PACKNUM 104857
#define TIME_WINDOW 4
#define UDP_PACK_SIZE 1154
#endif // !PARALLELCONSTANTS
